### ISSUE TITLE
Constructor ordering

### ISSUE THREAD

**Issue by ndryden** [Willtor/ThreadScan#2]
The methods `env_init` (in `env.c`) and `register_signal_handlers` (in `threadscan.c`) are both declared with `__attribute__((constructor))` with no priority given. Therefore, the order in which they run is not defined. However, `register_signal_handlers` requires the `g_threadscan_ptrs_per_thread` global variable to be properly initialized before it runs; this initialization is performed in `env_init`. If `register_signal_handlers` runs first, it initializes `g_tsdata` with garbage and everything is very unhappy.

The solution is to either have `register_signal_handlers` explicitly call `env_init` instead, or to give `env_init` a lower priority number (say 101) than `register_signal_handlers` (say 201).

**Comment by Willtor** [comment]
Thank you.  I've fixed it in my repo.  Threadscan is succeeded by Forkscan, but I'm creating a Threadscan branch for people who want to continue working with it.
